### ISSUE TITLE
Non-fatal error thrown when booting SNext

### ISSUE THREAD

**Issue by TeleKiwi** [Cube-Enix/SNext#18]
**Describe the problem**

An uncaught type error is thrown upon booting SNext. This is not fatal however, as you can simply ignore it and the console will boot successfully.
My exact error & stack trace is below;

      App threw an error during load
      TypeError: Cannot read properties of undefined (reading 'webContents')
          at Object.<anonymous> (/Users/telekiwi/Desktop/Code/SNext/src/main.js:56:24)
          at Module._compile (node:internal/modules/cjs/loader:1116:14)
          at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
          at Module.load (node:internal/modules/cjs/loader:988:32)
          at Module._load (node:internal/modules/cjs/loader:829:12)
          at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
          at loadApplicationPackage (/Users/telekiwi/Desktop/Code/SNext/src/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:110:16)
          at Object.<anonymous> (/Users/telekiwi/Desktop/Code/SNext/src/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:222:9)
          at Module._compile (node:internal/modules/cjs/loader:1116:14)
          at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)

**To Reproduce**

1. Boot SNext from the command line (npm start).

**Expected behavior**

SNext boots with no errors.

**Screenshots**

Error in the console
<img width="1440" alt="Screenshot 2022-08-22 at 19 40 04" src="https://user-images.githubusercontent.com/70376250/185995360-80dabe75-1a67-43b4-afe2-0c642660d689.png">

Error window from Electron
<img width="252" alt="Screenshot 2022-08-22 at 19 42 24" src="https://user-images.githubusercontent.com/70376250/185995372-9f067c06-16b6-4a04-aa6f-7103c667b6eb.png">

**Specs:**

 - OS: macOS Monterey 12.5.1
 - Console Build Version: source as of Monday, August 22nd @ 19:44pm BST
 
**Additional context**
This error happens on every boot, without fail.

**Comment by ShipmasterKyle** [comment]
Although this is listed as a macOS issue it is a global issue with how a good portion of the console actually renders data.

**Comment by ShipmasterKyle** [comment]
Patched
